def numlist_interactive() -> list[float]:
    # Collect and return a list of numbers read from the keyboard using
    # an interactive loop
    numlist: list[float] = []
    response: char = 'y'
    while response.strip().lower() == 'y':
        num = float(input('Please enter a number: '))
        numlist.append(num)
        response: char = input('Would you like to enter another? [y/N] ')
    return numlist

def numlist_neg_sentinel() -> list[float]:
    # Collect and return a list of numbers read from the keyboard using
    # a sentinel loop, using a negative number as the sentinel.
    # Downside: I can never put the sentinel into my list.
    sentinel = -9999999
    numlist: list[float] = []
    num_in: float = float(input('Please enter a number, or ' + str(sentinel)
                                + ' to quit: '))
    while num_in != sentinel:
        numlist.append(num_in)
        num_in = float(input('Please enter a number, or ' + str(sentinel)
                              + ' to quit: '))
    return numlist

def numlist_error_sentinel() -> list[float]:
    # Collect and return a list of numbers read from the keyboard using
    # the error generated by entering a non-number as the sentinel.
    numlist: list[float] = []
    while True: # Infinite loop?!
        try:
            num_in: float = float(input('Please enter a number, or '
                                        + ' anything else to quit: '))
            numlist.append(num_in)
        except ValueError:
            break
    return numlist

def numlist_nested() -> list[float]:
    # Collect and return a list of numbers read from the keyboard using
    # a nested loop (allows more than one number per line).  As with
    # numlist_error_sentinel, the error condition of a non-number is
    # used as a sentinel.
    numlist: list[float] = []
    while True: # Outer loop
        line_in = input('Please enter one or more numbers separated by '
                        + 'spaces, or anything else to quit: ')
        tokens = line_in.split() # Splits the line at white space
        if len(tokens) == 0: # Only white space on the input line
            break
        else:
            try:
                for tok in tokens: # Inner loop
                    numlist.append(float(tok))
            except ValueError: # Non-number in the input
                break
    return numlist
    
def indefinite_count(n: int) -> None:
    # Equivalent to for i in range(n)
    i: int = 0
    while i < n:
        print(i)
        i = i+1  # <- You have to remember to update the loop variable!

def main(args: list[str]) -> int:
    # An indefinite loop can do anything a definite loop can do
    #indefinite_count(10)

    #numlist: list[float] = numlist_interactive()
    #numlist: list[float] = numlist_neg_sentinel()
    #numlist: list[float] = numlist_error_sentinel()
    numlist: list[float] = numlist_nested()

    if len(numlist) > 0:
        print(numlist)
        print('\tSum:', sum(numlist), 'Average:', sum(numlist)/len(numlist))
    else:
        print('No numbers entered')
    
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
